export const CART_SAVE_REQUEST='CART_SAVE_REQUEST';
export const CART_SAVE_SUCCESS='CART_SAVE_SUCCESS';
export const CART_SAVE_FAIL='CART_SAVE_FAIL';

export const CART_DELETE_REQUEST='CART_DELETE_REQUEST';
export const CART_DELETE_SUCCESS='CART_DELETE_SUCCESS';
export const CART_DELETE_FAIL='CART_DELETE_FAIL';

export const CART_LIST_REQUEST='CART_LIST_REQUEST';
export const CART_LIST_SUCCESS='CART_LIST_SUCCESS';
export const CART_LIST_FAIL='CART_LIST_FAIL';

//export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REMOVEALL_ITEM = 'CART_REMOVEALL_ITEM';
export const CART_SEND_WAHTSAPP_MSG = 'CART_SEND_WAHTSAPP_MSG';