export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_REMOVEALL_ITEM = 'CART_REMOVEALL_ITEM';
export const CART_SEND_WAHTSAPP_MSG = 'CART_SEND_WAHTSAPP_MSG';