export const MUTUAL_FUND_LIST_REQUEST='MUTUAL_FUND_LIST_REQUEST';
export const MUTUAL_FUND_LIST_SUCCESS='MUTUAL_FUND_LIST_SUCCESS';
export const MUTUAL_FUND_LIST_FAIL='MUTUAL_FUND_LIST_FAIL';

export const MUTUAL_FUND_SAVE_REQUEST='MUTUAL_FUND_SAVE_REQUEST';
export const MUTUAL_FUND_SAVE_SUCCESS='MUTUAL_FUND_SAVE_SUCCESS';
export const MUTUAL_FUND_SAVE_FAIL='MUTUAL_FUND_SAVE_FAIL';

export const MUTUAL_FUND_DELETE_REQUEST='MUTUAL_FUND_DELETE_REQUEST';
export const MUTUAL_FUND_DELETE_SUCCESS='MUTUAL_FUND_DELETE_SUCCESS';
export const MUTUAL_FUND_DELETE_FAIL='MUTUAL_FUND_DELETE_FAIL';
